apiVersion: v1
kind: Service
metadata:
  name: codewizard-service
  labels:
    app: codewizard-admission-control
spec:
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: codewizard-admission-control
